clc;
clear all;
f= 1000;
l=100;
T=1/f;
t=(0:l-1)*T;
A=sin (2*pi*20*t);
B=sin (2*pi*50*t);
C=A+B;
subplot(3,3,1);
stem(t,A);
title("1 sine signal");
subplot(3,3,2);
stem(t,B);
title("2 sine signal");
subplot(3,3,3);
stem(t,C);
title("3 sine signal");
a1=abs(fft(A));
b1=abs(fft(B));
c1=abs(fft(C));
p1=a1(1:(l/2)+1);
p2=b1(1:(l/2)+1);
p3=c1(1:(l/2)+1);
F=f*(0:(l/2))/l;
subplot(3,3,4);
stem(F,p1);
title("magnitude response of a");
subplot(3,3,5);
stem(F,p2);
title("magnitude response of b");
subplot(3,3,6);
stem(F,p3);
title("magnitude response of c");
a2=unwrap(angle(fft(A)));
b2=unwrap(angle(fft(B)));
c2=unwrap(angle(fft(C)));
v1=a2(1:(l/2)+1);
v2=b2(1:(l/2)+1);
v3=c2(1:(l/2)+1);
subplot(3,3,7);
stem(F,v1);
title("phase response of A");
subplot(3,3,8);
stem(F,v2);
title("phase response of B");
subplot(3,3,9);
stem(F,v3);
title("phase response of C");
